/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaUsuario;

import NegocioVeficarDatos.verificarDatos;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Kendall
 */
public class reportesPeliculas extends javax.swing.JFrame {

    /**
     * Creates new form reportesPeliculas
     */
    JFreeChart grafica1;
    ChartPanel Panel;
    DefaultCategoryDataset Datos = new DefaultCategoryDataset();
    ArrayList datosReporte1Peliculas = new ArrayList();
    int numero =0;
    String genero1;
    String cancion1, cancion2;
    int maximo2, menor2;
    int indice;
    int indice2;
    
    public reportesPeliculas() {
        initComponents();
        this.getContentPane().setBackground(Color.gray);
        this.setLocationRelativeTo(null);
        this.setTitle("Reportes Peliculas");
        this.pack();
    }
    public void greficarMovie(){
        verificarDatos reporte1 = new verificarDatos();
        datosReporte1Peliculas = reporte1.reporte1Peliculas();
        if (datosReporte1Peliculas.isEmpty() == false) {
            for (int x = 0; x < datosReporte1Peliculas.size(); x++) {
                x = 0;
                indice = x;

                genero1 = (String) datosReporte1Peliculas.get(indice);
                cancion1 = (String) datosReporte1Peliculas.get(indice + 1);
                maximo2 = (int) datosReporte1Peliculas.get(indice + 2);
                cancion2 = (String) datosReporte1Peliculas.get(indice + 3);
                menor2 = (int) datosReporte1Peliculas.get(indice + 4);

                Datos.addValue(maximo2, cancion1, genero1 + " " + "+");
                Datos.addValue(menor2, cancion2, genero1 + " " + "-");

                indice2 = datosReporte1Peliculas.indexOf(genero1);
                int cont = 0;
                while (cont != 5) {
                    datosReporte1Peliculas.remove(indice2);
                    cont++;
                }
            }

            grafica1 = ChartFactory.createBarChart3D("Peliculas Más y Menos Comprados",
                    "Generos", "Compras", Datos,
                    PlotOrientation.VERTICAL, true, true, false);
        }else{
            JOptionPane.showMessageDialog(null, "No hay datos para graficar");
        }
    }
    public void mostrarEnPanel(){
        Panel = new ChartPanel(grafica1);
        PanelPeliculas.setLayout(new java.awt.BorderLayout());
        PanelPeliculas.add(Panel);
        PanelPeliculas.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        Reporte1 = new javax.swing.JRadioButton();
        Reporte2 = new javax.swing.JRadioButton();
        Reporte3 = new javax.swing.JRadioButton();
        btnGraficar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        PanelPeliculas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Opcionés");

        Reporte1.setBackground(java.awt.Color.gray);
        buttonGroup1.add(Reporte1);
        Reporte1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Reporte1.setForeground(new java.awt.Color(255, 255, 255));
        Reporte1.setText("Más vendidos y menos vendido por categoria");

        Reporte2.setBackground(java.awt.Color.gray);
        buttonGroup1.add(Reporte2);
        Reporte2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Reporte2.setForeground(new java.awt.Color(255, 255, 255));
        Reporte2.setText("Más comprados por Usuario");

        Reporte3.setBackground(java.awt.Color.gray);
        buttonGroup1.add(Reporte3);
        Reporte3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Reporte3.setForeground(new java.awt.Color(255, 255, 255));
        Reporte3.setText("Cantidad de disco mas vendidos por rango de fecha");

        btnGraficar.setBackground(new java.awt.Color(51, 204, 0));
        btnGraficar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGraficar.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        PanelPeliculas.setBackground(java.awt.Color.gray);
        PanelPeliculas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout PanelPeliculasLayout = new javax.swing.GroupLayout(PanelPeliculas);
        PanelPeliculas.setLayout(PanelPeliculasLayout);
        PanelPeliculasLayout.setHorizontalGroup(
            PanelPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelPeliculasLayout.setVerticalGroup(
            PanelPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 653, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Reporte3)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Reporte2)
                                    .addComponent(Reporte1))
                                .addGap(208, 208, 208)
                                .addComponent(btnGraficar)
                                .addGap(106, 106, 106)
                                .addComponent(btnRegresar)))
                        .addGap(0, 563, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Reporte1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Reporte2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGraficar)
                            .addComponent(btnRegresar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Reporte3)
                .addGap(18, 18, 18)
                .addComponent(PanelPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        if (Reporte1.isSelected()) {///Se estan hacinedo Prubas con las graficas

            if (PanelPeliculas == null) {
                PanelPeliculas.remove(Panel);
                PanelPeliculas.repaint();
            } else {
                greficarMovie();
                mostrarEnPanel();
            }
        } else if (Reporte2.isSelected()) {

            if (PanelPeliculas == null) {
                PanelPeliculas.remove(Panel);
                PanelPeliculas.repaint();
            } else {              
//                grafica();
//                mostrarEnPanel();
            }
        } else if (Reporte3.isSelected()) {

            if (PanelPeliculas == null) {
                PanelPeliculas.remove(Panel);
                PanelPeliculas.repaint();
            } else {               
//                grafica();
//                mostrarEnPanel();
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar una de las tres opciones");
        }
    }//GEN-LAST:event_btnGraficarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        accesoAdminstrador acc = new accesoAdminstrador();
        acc.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportesPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportesPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportesPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportesPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportesPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPeliculas;
    private javax.swing.JRadioButton Reporte1;
    private javax.swing.JRadioButton Reporte2;
    private javax.swing.JRadioButton Reporte3;
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
