/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VistaUsuario;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.jfree.chart.*;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author Kendall
 */
public class reportesDiscosMusica extends javax.swing.JFrame {

    /**
     * Creates new form reportesDiscosMusica
     */
    JFreeChart grafica1;
    ChartPanel Panel;
    int valor1,valor2,valor3;
    DefaultCategoryDataset Datos = new DefaultCategoryDataset();
    public reportesDiscosMusica() {
        initComponents();
        this.getContentPane().setBackground(Color.gray);
        this.setLocationRelativeTo(null);
        this.setTitle("Reportes Musica");
        this.pack();
        
        
    }
    public void grafica(){
        Datos.addValue(valor1, "Más Vendido", "Disco más vendido");
        Datos.addValue(valor2, "Menos Vendido", "Disco menos vendido");
        Datos.addValue(valor3, "Iguales", "Iguales");
        
        grafica1 = ChartFactory.createBarChart("Visitas diarias",
        "Días", "Visitas", Datos,
        PlotOrientation.VERTICAL, true, true, false);
    }
    public void mostrarEnPanel(){
        Panel = new ChartPanel(grafica1);
        jPanel1.setLayout(new java.awt.BorderLayout());
        jPanel1.add(Panel);
        jPanel1.validate();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jrbMasMenosVendidos = new javax.swing.JRadioButton();
        jrbComprasPorUser = new javax.swing.JRadioButton();
        jrbPorRango = new javax.swing.JRadioButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGraficar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jrbMasMenosVendidos.setBackground(java.awt.Color.gray);
        buttonGroup1.add(jrbMasMenosVendidos);
        jrbMasMenosVendidos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbMasMenosVendidos.setForeground(new java.awt.Color(255, 255, 255));
        jrbMasMenosVendidos.setText("Más vendidos y menos vendido por categoria");

        jrbComprasPorUser.setBackground(java.awt.Color.gray);
        buttonGroup1.add(jrbComprasPorUser);
        jrbComprasPorUser.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbComprasPorUser.setForeground(new java.awt.Color(255, 255, 255));
        jrbComprasPorUser.setText("Más comprados por Usuario");

        jrbPorRango.setBackground(java.awt.Color.gray);
        buttonGroup1.add(jrbPorRango);
        jrbPorRango.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jrbPorRango.setForeground(new java.awt.Color(255, 255, 255));
        jrbPorRango.setText("Cantidad de disco mas vendidos por rango de fecha");

        jPanel1.setBackground(java.awt.Color.gray);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(153, 153, 153), null));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 414, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Opciones");

        btnGraficar.setBackground(new java.awt.Color(51, 204, 0));
        btnGraficar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnGraficar.setForeground(new java.awt.Color(255, 255, 255));
        btnGraficar.setText("Graficar");
        btnGraficar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficarActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(255, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jrbComprasPorUser)
                            .addComponent(jrbPorRango)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jrbMasMenosVendidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                        .addComponent(btnGraficar)
                        .addGap(120, 120, 120)
                        .addComponent(btnRegresar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGraficar)
                            .addComponent(btnRegresar))
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jrbMasMenosVendidos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jrbComprasPorUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbPorRango)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGraficarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficarActionPerformed
        if(jrbMasMenosVendidos.isSelected()){///Se estan hacinedo Prubas con las graficas
            
            if(jPanel1 == null){
                jPanel1.remove(Panel);
                jPanel1.repaint();
            }else{
                valor1 = 15;
                valor2 = 20;
                valor3 = 30;
                grafica();
                 mostrarEnPanel();
            }
        }else if(jrbComprasPorUser.isSelected()){
            
            if(jPanel1 == null){
                jPanel1.remove(Panel);
                jPanel1.repaint();
            }else{
                valor1 = 5;
                valor2 = 10;
                valor3 = 25;
                grafica();
                 mostrarEnPanel();
            }
        }else if(jrbPorRango.isSelected()){
            
            if(jPanel1 == null){
                jPanel1.remove(Panel);
                jPanel1.repaint();
            }else{
                valor1 = 20;
                valor2 = 39;
                valor3 = 35;
                grafica();
                 mostrarEnPanel();
            }
            
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una de las tres opciones");
        }
    }//GEN-LAST:event_btnGraficarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(reportesDiscosMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(reportesDiscosMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(reportesDiscosMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(reportesDiscosMusica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reportesDiscosMusica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraficar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jrbComprasPorUser;
    private javax.swing.JRadioButton jrbMasMenosVendidos;
    private javax.swing.JRadioButton jrbPorRango;
    // End of variables declaration//GEN-END:variables
}
